#### Posts
### Add a post  
POST http://localhost:8080/posts  
Content-Type: application/json  
Authorization: Bearer {{accessToken}}

{
    "title": "Example Title",
    "content": "Example content for the post"
}

### Get all posts  
GET http://localhost:8080/posts


### Get posts by sender  
GET http://localhost:8080/posts?sender=example_sender


### Update a post  
PUT http://localhost:8080/posts/<postId>  
Content-Type: application/json  
Authorization: Bearer {{accessToken}}


#### Comments
### Create comment
POST http://localhost:8080/comments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "postID": "postId",
  "content": "Nice post!",
}


### Get comments by postID
GET http://localhost:8080/comments/postID/:postID


### Get comments by commentID
GET http://localhost:8080/comments/commentID/:id


### Update comment
PUT http://localhost:8080/comments/:id
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "Updated comment",
}


### Delete comment
DELETE http://localhost:8080/comments/:id
Authorization: Bearer {{accessToken}}

#### Authorization

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ofekcohen@gmail.com",
  "password": "123456"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "ofek",
  "email": "ofek@gmail.com",
  "password": "123456"
}

### Refresh token
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

