### Add a post  
POST http://localhost:8080/posts  
Content-Type: application/json  

{
    "title": "Example Title",
    "sender": "example_sender",
    "content": "Example content for the post"
}

### Get all posts  
GET http://localhost:8080/posts


### Get posts by sender  
GET http://localhost:8080/posts?sender=example_sender


### Update a post  
PUT http://localhost:8080/posts/<postId>  
Content-Type: application/json  


### Create comment
POST http://localhost:8080/comments
Content-Type: application/json

{
  "postID": "postId",
  "content": "Nice post!",
  "sender": "Ofek"
}


### Get comments by postID
GET http://localhost:8080/comments/postID/:postID


### Get comments by commentID
GET http://localhost:8080/comments/commentID/:id


### Update comment
PUT http://localhost:8080/comments/:id
Content-Type: application/json

{
  "content": "Updated comment",
  "sender": "Ofek2"
}


### Delete comment
DELETE http://localhost:8080/comments/:id